version: '3.3'

services:
  web:
    restart: always
    # build: ./src
    build: 
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8004:8000
